language: python

python:
 - 3.4

install:
 - python setup.py install

script:
 - python setup.py test
 - python -m pyfilesync.console --version
 - python setup.py build_sphinx

notifications:
  slack: myspacecowboysteam:GpIsy0NNliVDL0sBQGwZBodO
